# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About me
    url: about/
    weight: 20
  - name: Research and Publications
    url: publications/
    weight: 30
  - name: Teaching and Conferences
    url: teaching/
    weight: 40    
  - name: Data
    url: data/
    weight: 50  
